### ISSUE TITLE
pacbrew.mydedibox.fr is down

### ISSUE THREAD

**Issue by glebm** [PacBrew/pacbrew-pacman#1]
From https://github.com/diasurgical/devilutionX/runs/6014007183?check_suite_focus=true

> error: failed retrieving file 'pacbrew.db' from pacbrew.mydedibox.fr : Connection timed out after 10001 milliseconds

**Comment by Cpasjuste** [comment]
Hi,

Yes unfortunately there is a hardware problem with my dedicated server... It will probably take a few days for me to restore it as they said it's dead and no other server with the same sepcs are currently available...
I'll let you know when it's solved.

**Comment by glebm** [comment]
Thank you!

**Comment by Cpasjuste** [comment]
Hi,

The server should be up and running again.
